export enum TerrainDebugViewMode {
  Final = 0,
  GrassWeight = 1,
  DirtWeight = 2,
  RockWeight = 3,
  SnowWeight = 4,
  Height = 5,
  Slope = 6,
  TriplanarBlend = 7,
  Erosion = 8,
  RawHeight = 9,
  Flow = 10,
  River = 11,
  Lake = 12,
  Sediment = 13,
  RiverWidth = 14,
  WaterTransition = 15,
  Resource = 16,
  Coal = 17,
  Iron = 18,
  Copper = 19
}
